"""
Clash Royale unit and state label definitions.
Ported from KataCR/katacr/constants/label_list.py and state_list.py
"""

# All detectable unit types (150+ units)
unit_list = [
    # Towers and structures
    'king-tower',
    'queen-tower',
    'cannoneer-tower',
    'dagger-duchess-tower',
    # Bars and UI elements
    'dagger-duchess-tower-bar',
    'tower-bar',
    'king-tower-bar',
    'bar',
    'bar-level',
    'clock',
    'emote',
    'text',
    'elixir',
    'selected',
    'skeleton-king-bar',
    # Units
    'skeleton',
    'skeleton-evolution',
    'electro-spirit',
    'fire-spirit',
    'ice-spirit',
    'heal-spirit',
    'goblin',
    'spear-goblin',
    'bomber',
    'bat',
    'bat-evolution',
    'zap',
    'giant-snowball',
    'ice-golem',
    'barbarian-barrel',
    'barbarian',
    'barbarian-evolution',
    'wall-breaker',
    'rage',
    'the-log',
    'archer',
    'arrows',
    'knight',
    'knight-evolution',
    'minion',
    'cannon',
    'skeleton-barrel',
    'firecracker',
    'firecracker-evolution',
    'royal-delivery',
    'royal-recruit',
    'royal-recruit-evolution',
    'tombstone',
    'mega-minion',
    'dart-goblin',
    'earthquake',
    'elixir-golem-big',
    'elixir-golem-mid',
    'elixir-golem-small',
    'goblin-barrel',
    'guard',
    'clone',
    'tornado',
    'miner',
    'dirt',
    'princess',
    'ice-wizard',
    'royal-ghost',
    'bandit',
    'fisherman',
    'skeleton-dragon',
    'mortar',
    'mortar-evolution',
    'tesla',
    'fireball',
    'mini-pekka',
    'musketeer',
    'goblin-cage',
    'goblin-brawler',
    'valkyrie',
    'battle-ram',
    'battle-ram-evolution',
    'bomb-tower',
    'bomb',
    'flying-machine',
    'hog-rider',
    'battle-healer',
    'furnace',
    'zappy',
    'baby-dragon',
    'dark-prince',
    'freeze',
    'poison',
    'hunter',
    'goblin-drill',
    'electro-wizard',
    'inferno-dragon',
    'phoenix-big',
    'phoenix-egg',
    'phoenix-small',
    'magic-archer',
    'lumberjack',
    'night-witch',
    'mother-witch',
    'hog',
    'golden-knight',
    'skeleton-king',
    'mighty-miner',
    'rascal-boy',
    'rascal-girl',
    'giant',
    'goblin-hut',
    'inferno-tower',
    'wizard',
    'royal-hog',
    'witch',
    'balloon',
    'prince',
    'electro-dragon',
    'bowler',
    'executioner',
    'axe',
    'cannon-cart',
    'ram-rider',
    'graveyard',
    'archer-queen',
    'monk',
    'royal-giant',
    'royal-giant-evolution',
    'elite-barbarian',
    'rocket',
    'barbarian-hut',
    'elixir-collector',
    'giant-skeleton',
    'lightning',
    'goblin-giant',
    'x-bow',
    'sparky',
    'pekka',
    'electro-giant',
    'mega-knight',
    'lava-hound',
    'lava-pup',
    'golem',
    'golemite',
    'little-prince',
    'royal-guardian',
    'archer-evolution',
    'ice-spirit-evolution',
    'valkyrie-evolution',
    'bomber-evolution',
    'wall-breaker-evolution',
    'evolution-symbol',
    'mirror',
    'tesla-evolution',
    'goblin-ball',
    'skeleton-king-skill',
    'tesla-evolution-shock',
    'ice-spirit-evolution-symbol',
    'zap-evolution',
]

# Create lookup dictionaries
idx2unit = dict(enumerate(unit_list))
unit2idx = {name: idx for idx, name in enumerate(unit_list)}

# Unit categories
tower_unit_list = [
    'king-tower',
    'queen-tower',
    'cannoneer-tower',
    'dagger-duchess-tower',
]

ground_unit_list = [
    'archer', 'archer-evolution', 'archer-queen', 'balloon', 'bandit',
    'barbarian', 'barbarian-evolution', 'barbarian-barrel', 'barbarian-hut',
    'battle-healer', 'battle-ram', 'battle-ram-evolution', 'bomb', 'bomb-tower',
    'bomber', 'bomber-evolution', 'bowler', 'cannon', 'cannon-cart', 'clone',
    'dark-prince', 'dart-goblin', 'dirt', 'earthquake', 'electro-dragon',
    'electro-giant', 'electro-spirit', 'electro-wizard', 'elite-barbarian',
    'elixir-collector', 'elixir-golem-big', 'elixir-golem-mid', 'elixir-golem-small',
    'executioner', 'fire-spirit', 'firecracker', 'firecracker-evolution',
    'fisherman', 'freeze', 'furnace', 'giant', 'giant-skeleton', 'goblin',
    'goblin-brawler', 'goblin-cage', 'goblin-drill', 'goblin-giant', 'goblin-hut',
    'golden-knight', 'golem', 'golemite', 'graveyard', 'guard', 'heal-spirit',
    'hog', 'hog-rider', 'hunter', 'ice-golem', 'ice-spirit', 'ice-spirit-evolution',
    'ice-wizard', 'inferno-tower', 'knight', 'knight-evolution', 'lava-hound',
    'lava-pup', 'little-prince', 'lumberjack', 'magic-archer', 'mega-knight',
    'mighty-miner', 'miner', 'mini-pekka', 'monk', 'mortar', 'mortar-evolution',
    'mother-witch', 'musketeer', 'night-witch', 'pekka', 'phoenix-egg', 'poison',
    'prince', 'princess', 'rage', 'ram-rider', 'rascal-boy', 'rascal-girl',
    'royal-delivery', 'royal-ghost', 'royal-giant', 'royal-giant-evolution',
    'royal-guardian', 'royal-hog', 'royal-recruit', 'royal-recruit-evolution',
    'skeleton', 'skeleton-evolution', 'skeleton-king', 'skeleton-king-skill',
    'sparky', 'spear-goblin', 'tesla', 'tesla-evolution', 'tesla-evolution-shock',
    'tombstone', 'valkyrie', 'valkyrie-evolution', 'wall-breaker',
    'wall-breaker-evolution', 'witch', 'wizard', 'the-log', 'x-bow', 'zappy',
]

flying_unit_list = [
    'arrows', 'axe', 'baby-dragon', 'bat', 'bat-evolution', 'flying-machine',
    'fireball', 'giant-snowball', 'goblin-ball', 'goblin-barrel', 'inferno-dragon',
    'lightning', 'mega-minion', 'minion', 'phoenix-big', 'phoenix-small',
    'rocket', 'skeleton-barrel', 'skeleton-dragon', 'tornado', 'zap',
]

spell_unit_list = [
    'arrows', 'clone', 'earthquake', 'fireball', 'freeze', 'giant-snowball',
    'goblin-barrel', 'graveyard', 'lightning', 'poison', 'rage', 'rocket',
    'skeleton-king-skill', 'tesla-evolution-shock', 'tornado', 'zap',
]

object_unit_list = [
    'axe', 'dirt', 'goblin-ball', 'bomb',
]

other_unit_list = [
    'bar', 'bar-level', 'clock', 'dagger-duchess-tower-bar', 'elixir',
    'emote', 'evolution-symbol', 'ice-spirit-evolution-symbol',
    'king-tower-bar', 'skeleton-king-bar', 'text', 'tower-bar',
]

bar2_unit_list = ['dagger-duchess-tower-bar', 'skeleton-king-bar']

# State definitions (for unit belonging: friend=0, enemy=1)
idx2state = {
    0: '0',  # friend
    1: '1',  # enemy
}

state2idx = {
    '0': 0,
    '1': 1,
}
